export const rows = [
    { title: 'Funding Target', desc: '100,00.00 EUR' },
    { title: 'Minimum Funding Target', desc: '50,00.00 EUR' },
    { title: 'Borrower Interest', desc: '3.00 %' },
    { title: 'Investor Interest', desc: '0.00 %' },
    { title: 'Platform Interest', desc: '3.00 %' },
    { title: 'Loan Period, Months', desc: '6' },
    { title: 'Schedule Type', desc: '0' },
    { title: 'Repayment', desc: '0' },
    { title: 'Interest Repayment', desc: 'regular intervals pursuant to an interest' },
    { title: 'Frequency og interest payment', desc: '12' },
    { title: 'Minimum interest(month)', desc: '0' },
    { title: 'Stage Loan', desc: 'Yes' },
    { title: 'Stage', desc: '0' },
    { title: 'LTV', desc: '0.00 %' },
    { title: 'LTVA', desc: '0.00 %' },
    { title: 'Projected LTV', desc: '0.00 %' },
];